name: Run My App

on:
  push:
    branches:
      - main  # Change this to your branch name if different
  pull_request:

jobs:
  run-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Change to your version

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # Modify if needed

      - name: Run the app
        env:
          API_KEY: ${{ secrets.API_KEY }}  # Load the API key
        run: python my_script.py  # Replace with your script
